<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Testcontainers.MsSql" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/TaleQuilt.Api/TaleQuilt.Api.csproj" />
  </ItemGroup>
</Project>
